### PR TITLE
600+ additional colors

### PR DESCRIPTION
**Pull request by michael-house**
Additional colors available
Fixed merge issue with name change

### CODE REVIEW

**Comment by jbienzms** [comment]
Hey @michael-house. I'm really sorry I didn't see this PR until after I refactored that behavior into two two separate ones. Would you like to resubmit the PR and I can merge it in, or do you want me to just copy your code into my current branch?

**Comment by michael-house** [comment]
I'll take a look at refactoring it, but it might be a few days. If you're preparing the code for something that's time sensitive, feel free to just copy in the code yourself. Thanks for updating the code, glad to see some work being put into this project!

**Comment by jbienzms** [comment]
I'm working on the sample some more today. I'll just copy your code in. Thanks again Michael.

**Comment by jbienzms** [comment]
These changes have been incorporated manually in 2738e5e8b5393c397ce985bbe60a7eb8410292dc.

**Comment by jbienzms** [comment]
Closing this item as the proposed changes have been manually merged.

**Pull request closed without merging**
